---
- name: gather ios facts
  hosts: all 
  gather_facts: false 
  connection: network_cli

  tasks:
    - name: gather ios facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: gather routes
      cisco.ios.ios_config:
        command: show ip route
